/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RegisterGameIdLazyImport = createFileRoute('/register/$gameId')()
const JustoneGameIdLazyImport = createFileRoute('/justone/$gameId')()
const HubGameIdLazyImport = createFileRoute('/hub/$gameId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RegisterGameIdLazyRoute = RegisterGameIdLazyImport.update({
  path: '/register/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/register.$gameId.lazy').then((d) => d.Route),
)

const JustoneGameIdLazyRoute = JustoneGameIdLazyImport.update({
  path: '/justone/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/justone.$gameId.lazy').then((d) => d.Route),
)

const HubGameIdLazyRoute = HubGameIdLazyImport.update({
  path: '/hub/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hub.$gameId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/hub/$gameId': {
      preLoaderRoute: typeof HubGameIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/justone/$gameId': {
      preLoaderRoute: typeof JustoneGameIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/register/$gameId': {
      preLoaderRoute: typeof RegisterGameIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  HubGameIdLazyRoute,
  JustoneGameIdLazyRoute,
  RegisterGameIdLazyRoute,
])

/* prettier-ignore-end */
